# Terraform will be unable to decode this file if it does not contain valid YAML
# You can retain `---` (start of the document) to indicate an empty document.
inbound_rules:
  rdp_admins_inbound_allow:
    disabled: ENC[AES256_GCM,data:cfJ8RIQ=,iv:SkAPDOEw2Qu2g3jEYQymoZFGwWVmyH9MIZjxhJZzVXY=,tag:AWrazyp8i677U/BHqPNxaA==,type:bool]
    deny: ENC[AES256_GCM,data:+8YpQLs=,iv:2JWk7jUKaoDI1qlj5/cbCzLv7k5umSNK2e6qfSQj8vk=,tag:Too7Uxp8pEL3viIacvUC4w==,type:bool]
    description: ENC[AES256_GCM,data:BCnOBXBz9yjgwwJdbLDtnW8cG122fbWCTQ==,iv:4bkrONjm9+UhAyfjL5U+7b4RDF8ndX3EOU04gEKFZm8=,tag:TGN7xqBhD9YWHDrZwVlbdg==,type:str]
    priority: ENC[AES256_GCM,data:7bXy,iv:DMJOIRMygHjsEcATch3/Xz1Our6+2a7SReMZtZAqUGQ=,tag:biw/BdMTtruocEAGSD6T5w==,type:int]
    protocol: ENC[AES256_GCM,data:7x1M,iv:c/fhJdNKo5PUuLMbHjGU26NfkP8GNiMTmIIIsITi04A=,tag:I9SBmhJVmVcjEsTIJcNYQg==,type:str]
    source_port_range: ENC[AES256_GCM,data:Wg==,iv:QOekG8KbmETJ17ivx5FqTeW+dQrHCmIcD0xWbx630qI=,tag:BQVmLh7Ik3AJt52c4TjZlw==,type:str]
    destination_port_range: ENC[AES256_GCM,data:ufl+Yw==,iv:wouyDnn2pMntT/6eWhFvR6vGk7qiVgxrqZixzoUoeJ0=,tag:kyZkwnmABWDu/wP7jZR97Q==,type:str]
    source_address_prefixes:
      - ENC[AES256_GCM,data:JNO797P+p03q,iv:+wM5RgcAWZg9/C9FzmLDDGC+/xIQUpj9WRluyzWluOg=,tag:xAT5bdtlzk47FiyP6ZZC/Q==,type:str]
    destination_address_prefix: ENC[AES256_GCM,data:gA==,iv:LU8sKzdZuSQBRLkY5y4MFgxpxwwgFVMlsrcY2e6OcAg=,tag:D7QgXS/y1+wy9QWIum8EPw==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:MKea,iv:DSr3Ul+K1ZHxGQHSusvt6z5ja9h23/YIX/iqNacAvnQ=,tag:KMvm3nMI6/URgb7Z2rWFEA==,type:str]
  winrm_admins_inbound_allow:
    disabled: ENC[AES256_GCM,data:GWrHJr4=,iv:aezMKXIsBinRGfoElE4Prt4IlOylZmkzBAIT7rjCw2Y=,tag:oC6zTthsNa4vRugDvs8zqQ==,type:bool]
    deny: ENC[AES256_GCM,data:7YHY3rQ=,iv:yaCNxzaT2KlIIpTmxaCfCiGX5+haFQQCaZ23VDlhM/w=,tag:qQWOH6bLl2wECVLCnIklbg==,type:bool]
    description: ENC[AES256_GCM,data:6en0MuvNDMHzfrYBkK8mZKwGBJc3f/5RNkz1w9w=,iv:47xCqXFdzlq8kGXq3Jwjax+BDBs785fdewWsqkVtDFk=,tag:DPdCaP91xJSAZXHVa1lyNA==,type:str]
    priority: ENC[AES256_GCM,data:YDtM,iv:uiThH54+L2DESkqU3uHIc9RkvpakhZ4Fju3laP8nSJE=,tag:T9j/rdk6NWJeLGRSc7wFJQ==,type:int]
    protocol: ENC[AES256_GCM,data:S7X+,iv:QhhrpRMddl2Wd3MfXILkryhcMthsuTRxOlbD6VB2aUQ=,tag:GtUvbVRQNv9h/nixMq9iEg==,type:str]
    source_port_range: ENC[AES256_GCM,data:RA==,iv:KZI8+eEN78htskYKC7E3FSh6s71WlklZv0DV1gMIMNE=,tag:Q12Y56t8WspyfuVvK75z1A==,type:str]
    destination_port_range: ENC[AES256_GCM,data:owgv9A==,iv:qVV0CIax3fgmt0nPYyTJ5ThPHyh50QWMquhJU+n++7w=,tag:H+3Vp3G0chSZjmzu6nQovQ==,type:str]
    source_address_prefixes:
      - ENC[AES256_GCM,data:SWnSwkFwQc2A,iv:F85iUizvCWjH7NYEn4wJBqbm8Pw+Nd8azUBBKjxeiJs=,tag:FjzzOo+mxH24JHc0cpBG9w==,type:str]
    destination_address_prefix: ENC[AES256_GCM,data:aQ==,iv:uAhbHLc58GntQWfLsN2b2Hwaoz2MdnE5nEcvs+ImgDc=,tag:+4JJ75hO99ESn8l3nMgvvw==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:qy1o,iv:jebcwIi2DhRNEY3UroQ/N/JcWNNk+H3Z/r+rcjScwc4=,tag:Ztceana4G279DbqRTJTtpg==,type:str]
outbound_rules:
  all_outbound_allow:
    disabled: ENC[AES256_GCM,data:AXT81A==,iv:Wc4vD41JtUFaN2qbeiEWaV5eewF3XbiSkIHPaApS/WY=,tag:tMsaQFTg2PI/zY5kyqHs/g==,type:bool]
    description: ENC[AES256_GCM,data:nk/0hhcSB25CpMzE/KUvYsxZ62lqTO1fAg==,iv:ExdL/LXlokV8/+bIJBeCZSnBM9GNbIX9EQJcizDhYZ4=,tag:gZQ4wzl7oYwSfxtTqyg/aA==,type:str]
    priority: ENC[AES256_GCM,data:NJw5,iv:l96QoPyMkaj8GNIIuhuG2LrPXm17GHSrtYDPXOmoEB8=,tag:quQKi03bB4BATAUoS4U/qA==,type:int]
    protocol: ENC[AES256_GCM,data:3Q==,iv:4oBIo0jL6HUNeGVU23tYWSUz8VxiZzoe2Y1hvRDG5hY=,tag:lob4I7in9E8t3E858AF2VA==,type:str]
    source_port_range: ENC[AES256_GCM,data:sQ==,iv:sNPaJ4ooPqWQDsXlOp7u8IO7wt4Em55/KvOo4Ghs2dU=,tag:yHnhEAGPYCiytZ1jc2KCKA==,type:str]
    destination_port_range: ENC[AES256_GCM,data:kQ==,iv:fNPtqdBuABO0JMFjRn3gP69oRyLn883Y9JjSfDhKBpY=,tag:XpUujXXAo/T9u8wnQ4EjRw==,type:str]
    source_address_prefix: ENC[AES256_GCM,data:jA==,iv:3TVeAFZTitFYTiIzQWfJ5ClX7bnBfPRHhvRZNDn/ZrI=,tag:ZmnNJ9y9JsAyTmOfPgLA3w==,type:str]
    destination_address_prefix: ENC[AES256_GCM,data:VQ==,iv:gphHOAUK8hUT1A7cPTpsOEZEnAXhY26A2n+1xMiORNM=,tag:7OeJq9lMcLHopTVsNA0hfQ==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:rFhy,iv:zpEtFR2++ONNbaYoKDQPsFn0b9y/jwQKotpx8hu91mo=,tag:BiFRf7hVu18pA3CxoP7bqg==,type:str]
  rfc1918_outbound_allow:
    disabled: ENC[AES256_GCM,data:QDatrA==,iv:N3+TkBQ7Q7jkBNnboTCAudnj3uD3qm5ulDgDRkes5DQ=,tag:iazRY+aOjgfgygeKrrDwbw==,type:bool]
    description: ENC[AES256_GCM,data:K27p2VKEU1NndKFoj/92epvM4cfB4lhVVPTE4AuJtFc=,iv:Mei//46UrZrTpS68Th1V0WUABTXfHoaggZWUBVrLQ+o=,tag:fOcTyEwrr8s9XCwxnmPqZA==,type:str]
    priority: ENC[AES256_GCM,data:pCOT,iv:NxUNn6sCpx1N/QWKu0wa8prlyVwGI/S9SofgBvUy8xk=,tag:q3RjJbK7YFF3Jl5fsv5EVA==,type:int]
    protocol: ENC[AES256_GCM,data:GA==,iv:mYB6Ogz20KJXfymxJHRLrxFCku7ToizksOet9vpTpkw=,tag:JSW9MFFmtshDlFAuzTgWwQ==,type:str]
    source_port_range: ENC[AES256_GCM,data:mg==,iv:eTV8vfZ+HUPE1Y1EHtff421ibJXQoFWCtMpsKml0pJM=,tag:QTOTCwSiKUSe1hR68ZjolQ==,type:str]
    destination_port_range: ENC[AES256_GCM,data:uw==,iv:UYHB5hzzusZ72bXu9CoNTTGpMvBa+5D/a15kiHWGcSA=,tag:kNATWn3E3va3hXTTEuys/Q==,type:str]
    source_address_prefix: ENC[AES256_GCM,data:uw==,iv:pMXACUrsM94HQNnwDnWraK7xq49hCv5jRDy82RrNOdU=,tag:ZcSN5yzHFpEjRYC4gSjCxw==,type:str]
    destination_address_prefixes:
      - ENC[AES256_GCM,data:Bgvv4JMsPCJwYQ==,iv:wXWfe48ZOejPl+On6ZFq4V2W1F/iQXOOPtoQuB0eACw=,tag:Qfg8eCVxyO3jyxeFkqPmVQ==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:8eDx,iv:QvnSiNdSR/osND41Ngp3bVtb4Bg3bZdJCVA5ZIDhfQQ=,tag:XLeCIaIkfeMH0wUBtB1FTA==,type:str]
sops:
  lastmodified: "2026-05-14T21:52:36Z"
  mac: ENC[AES256_GCM,data:qFDuiVeIIGz20KiA8rcEMTmoq5AAZzyJ4woaFCs1X3ujT+rhvHaKxnqbsnzN8oVyqP4Nvpq5gsmqLTKQzTDWSAatpXiqOCxV0LsUhjSyHqp6mdWNS4OKUBsv1zGE+UwHvxB15q0YY9Dbz1P1TaPpWAW3lHMzKt9n0L1T0cw3xF0=,iv:Njv9l0hNt3YnylT2vCfILcFRBfktU2T3SPy7G1FstPM=,tag:X7O5QAE1Y2zAagwmnBZuzQ==,type:str]
  pgp:
    - created_at: "2026-05-14T21:52:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA4KMO5ZgOOZwAQwAhGteFu+8eitZF8+AE+Hq46bWUCcWYLlV4Pb2Z+c3GQwb
        BhQ8GGapTex/TjYwT4DvLNvGDDX6/dC2l3csZt3DJppKa8SGWTKgSTQvreenr6zz
        Smq0sQ6bVtrwIacjVagCLSHFHd0PFRF7b7qWXSERWfS8o8S1j8hRevyOh9CrK0qu
        UXbQZODHYQ6/wt/M3Q447iaf8yF8eLt1heZqJDpN0Z7DGxE7efLP0Fr1sAbZfV9u
        D8evue2BNEBbM8SYWo9KC5ij+j4jnfvu3unSeH4i0YPCja4/LbsfKrwQJhlzh38Q
        2mzGs5bHnn780OrElKWjT2Xthtda8Z6qF2gy8FTmhf4Q6YOPQBvPe4HQJG7NKMLa
        zBiY/SceOThgjdN1bBAhl91tCmZfgI8wlTJnz1ORqUVEv709ZXoW3zQR9sXw7wz8
        Up0GiM8vJTtwupV6V47afZwQ0oRTLIVTgi5ey3sTPgcV/wJvUrl9dCaizbpatOwy
        FG0IWIQJ3uBRbWAahAZT0l4BLui00IAn2/Zpe2aKVh0iiQUkobhjCB9DldzdP8MM
        d/TdWMHkprpRvEs2kEH6npuoJck3MczEoH12Vcamk9Haxv4ExvHEb99zKXT0RoKd
        iqnvUb08jA3W8XYavbYt
        =oh60
        -----END PGP MESSAGE-----
      fp: E751B57856FF4B3B7B4C7F5F3E041E30885ADDC3
  encrypted_regex: ^.+$
  version: 3.12.1
