# Terraform will be unable to decode this file if it does not contain valid YAML
# You can retain `---` (start of the document) to indicate an empty document.
inbound_rules:
  rdp_admins_inbound_allow:
    disabled: ENC[AES256_GCM,data:dXgCemM=,iv:/mgNqOYrLcuhMv/QlEtkNi0a/7TqxBIOf5wQpGuiSD0=,tag:hfMg+0R6i14RtErGv8lTzA==,type:bool]
    deny: ENC[AES256_GCM,data:80Hma5o=,iv:adO8JfJ4b1Og6A4H5/yYb4ETtJuP1aqELIfJe6QTC3Y=,tag:jeQOqtKUeIdOeSnzjbV18A==,type:bool]
    description: ENC[AES256_GCM,data:UeoujB4ydIwsg6vGadn+cXemLs9A6GVdJg==,iv:tsNSyl3bY5YXw7a27CW2V5moAViatj4L2b2dML2aZxU=,tag:DlEtiWRSecxAX/gpQNILZQ==,type:str]
    priority: ENC[AES256_GCM,data:fsjd,iv:h2iuEEd/CyoJhYSaQZRRj0vxolMll22vrP3E+v4bIoo=,tag:FYzVPI5gs6/VNMcmFxB5yQ==,type:int]
    protocol: ENC[AES256_GCM,data:iOJY,iv:JJeBc6ZLQqfU+HRuQN2bT4S+FZKRqz2mv124wqlmpOk=,tag:+OdOKW6dBdwF6Urjw2/MiA==,type:str]
    source_port_range: ENC[AES256_GCM,data:4w==,iv:p1ncU9RnZi55HqK4Y8B0zyFNLZoMyCygELtz2YXizRM=,tag:atF6MY+dMsc3IUjGHr8IWg==,type:str]
    destination_port_range: ENC[AES256_GCM,data:hrL2Cg==,iv:LSz/bccoebKEvNXBRLIQvXuv+9m7/Vqii1hs1jvNiTk=,tag:K2be44CiFsCpnb8fDiZS6A==,type:str]
    source_address_prefixes:
      - ENC[AES256_GCM,data:hbjUSs09cE3F,iv:4t/kLPmoUWYctSmVDtthkWSOGs5ZoEzba73MP0njv1w=,tag:cwQ3WUe/74Rtthv7s3vJIg==,type:str]
    destination_address_prefix: ENC[AES256_GCM,data:Yg==,iv:8chflsGDbk/bTK2snJVwVn0vA70pfpjlt70G7Zy4Q6g=,tag:+UrHJTVjUuIu1ypkwgKUqQ==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:+cqq,iv:2hs1KevsUIJHLmd6FKm2k9qKsVMZmCyLzJsYqOExyzw=,tag:HnHJ06z7LmLnR52g3bMlWw==,type:str]
  winrm_admins_inbound_allow:
    disabled: ENC[AES256_GCM,data:6vMXUA==,iv:NV6buNRXTHM/aDnaxz+F6SjfhrzWKK0dB2+VjhAyNzI=,tag:+zxoGQMqTxS/glKlOBWgrA==,type:bool]
    deny: ENC[AES256_GCM,data:4unEKb4=,iv:0dyiTMp+qo0Z8r3oZ50F8ihQYhbOz9ZdOQUqigRPMoc=,tag:OFTd8Hk1xauBp7Jwj88Rew==,type:bool]
    description: ENC[AES256_GCM,data:Eb7aW5zzHVuVzVbjVaS+xfXRoP6ifYAMUNN43n8=,iv:8QFkF0PLxblrAtOPTjyB4laJ5jKQU29yUnnHlQ1+H2k=,tag:tP5mVfrLXObHNF2QsyXFfg==,type:str]
    priority: ENC[AES256_GCM,data:DUhE,iv:kcNenX6ANjyG/wEIyjkce7J6ohA4HVQ/Pm3JX8Am9hI=,tag:GTNI4qK9CRqyHDO3RNfcmg==,type:int]
    protocol: ENC[AES256_GCM,data:2ZWH,iv:1eDmXJmKkEE5x3PFQfVqNBtlxtPH7D+cdwPGivch7bk=,tag:14D/wz8ci3LZ0KrI1H/1cw==,type:str]
    source_port_range: ENC[AES256_GCM,data:Gw==,iv:vIQK2UEuJFX4loN7u1lU7rS+F6L8BQWHFmBvlyWq1AU=,tag:PyvMMZxN20by/EvnBbWGiQ==,type:str]
    destination_port_range: ENC[AES256_GCM,data:FsGHEA==,iv:84Rn58tGsR+kdQoeel/wA3lTFsVJylMmsUPpGxz7jpA=,tag:8uYaQgcO9njzwiUhO1gsrg==,type:str]
    source_address_prefixes:
      - ENC[AES256_GCM,data:kYNIczKt2Nk2,iv:L97AOV+wSL119O/61Ft1KJ0T35fPgTfvAyRZ4L+zjjQ=,tag:XQA9OAH2il7tOdsCIHFlPg==,type:str]
    destination_address_prefix: ENC[AES256_GCM,data:RQ==,iv:9mCB8Ay/RQOUlpChwtXfYDbwL9x9KdsvayohSqlyHZI=,tag:Ak26cPE95s5YAm1x89F7yw==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:6HVa,iv:Nx0t6rzMVfo4dO9PfQBIpLHSG8BdgYnwDKuNRhgVSDQ=,tag:CmOXSV/q+tes3Fbx+nILrA==,type:str]
outbound_rules:
  all_outbound_allow:
    disabled: ENC[AES256_GCM,data:6BVOTg==,iv:RsiYOPyDE2ImK2UVoTlFXSif3h50jVjiKdaNEpp057Y=,tag:0Z8kWR441o3l8W4YMfnLGw==,type:bool]
    description: ENC[AES256_GCM,data:v/ZUIEvmo0wnWnPO1oUF7U4xQLhYVkH0pw==,iv:eEbIwsjDfcZw9hlbBU/91FrGNpFCfBLydr6I9psOtIM=,tag:WCkLm72LRUf0bRS29n8PiQ==,type:str]
    priority: ENC[AES256_GCM,data:dWJn,iv:KcK8esQyr0N6nPrn13eaqi4b1qNUpr2P2Tl1HyYVLAs=,tag:al3atGPrSm6bZ/bXeiHRZg==,type:int]
    protocol: ENC[AES256_GCM,data:9g==,iv:tL4EYN+TX+3iIgcgRbmoenKULWIoFzs1X7FaXGYGC8M=,tag:ZgvIFmTltGq8+pRfi10X2A==,type:str]
    source_port_range: ENC[AES256_GCM,data:eQ==,iv:5hoRDbuZw4GbF4IEbezF4icYtfxlKmR0/D0Vp4c5WPc=,tag:5LZwHWU92wCS8Ko/nmPwlQ==,type:str]
    destination_port_range: ENC[AES256_GCM,data:Ug==,iv:xNrAZx3unh4jtvMI4lsKj1BTF32OucsaDcSBEr0hCuE=,tag:H7cmAL1Vkmn3+AEaO7POrQ==,type:str]
    source_address_prefix: ENC[AES256_GCM,data:ow==,iv:FxSxlbq0Ya2r91V29NFquS0lxysrLkWUTaDudAWRgf4=,tag:RwSm8RpRYfSZDlfQcJchXg==,type:str]
    destination_address_prefix: ENC[AES256_GCM,data:Gw==,iv:j7VSI1u9ct2q6B8cpw3jvnBlrUwQ28UTtaJtR268+Ws=,tag:lI+OqtOdDtA2vdWKhib00g==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:ARQ1,iv:d/aufpFETlPt2Gqq/XaIA4PL8VDeTVz0gMWHqacqhHI=,tag:giQP1zxN4m0Pq9ABxq026g==,type:str]
  rfc1918_outbound_allow:
    disabled: ENC[AES256_GCM,data:6tTwcg==,iv:uKbJaph0wSthacXxMP8EjC6AoijnzOtwewcDagVPnko=,tag:ETlHG/dxdIlUN+Dwj32EVQ==,type:bool]
    description: ENC[AES256_GCM,data:BlNofXxoMPO7LTrxrKrdWBRo4j8qDNuW7d9+hX3RDnY=,iv:FBxkbSL8Uqsq8bpssxnJSachV1FJyY3ZRIlHykzb9fg=,tag:ZDw1jB483YYmqbSYUzdTFg==,type:str]
    priority: ENC[AES256_GCM,data:VrAS,iv:URM85FhAUYKg2FOHbiRwguyLV2RrgxMSMMF+j32uWOw=,tag:PDskd1kF7jfTvTfnllSfpw==,type:int]
    protocol: ENC[AES256_GCM,data:Dg==,iv:3wvDzq9VWhXTGEK1nMF0/fuJEPFj0Kf4fJxz0ZCIX+Y=,tag:Ezjqx3ZRJkTkR1W46w1w8g==,type:str]
    source_port_range: ENC[AES256_GCM,data:+w==,iv:XvwsZ9n+Cktl6FMB/nzqFttlzy4PVLLujgDubRw6xJs=,tag:880qa0DQrp9T66wXJ2i+gA==,type:str]
    destination_port_range: ENC[AES256_GCM,data:zA==,iv:kjA9YEGAO9Yll1EIhnW+U5S92gnmNUlUuh7w7c3IS3I=,tag:fp+RWwvJiHCBoPZPTbFecw==,type:str]
    source_address_prefix: ENC[AES256_GCM,data:Cg==,iv:dpnyWTGOC3BFt8uEy9tLHLq09mAtLgqwn0fqCYJ+bTA=,tag:BZPwfsjhvmBBhDI/L9/uwA==,type:str]
    destination_address_prefixes:
      - ENC[AES256_GCM,data:bvEDp9trDNOmkA==,iv:L/YoQlQ6bhYWI4ihJlAcBgmLPW7sRkUmyCXhHZ/Gets=,tag:BeA9gA5jgdJYeG2CC/Qt7Q==,type:str]
    associations:
      subnets:
        - ENC[AES256_GCM,data:yfcp,iv:rCrys8opIGNUBhqIKKHST9bSFaOwFI4zyfJBkNWJe2I=,tag:dwvPds0OKNOX76nmQOEn1w==,type:str]
sops:
  lastmodified: "2026-05-14T22:51:17Z"
  mac: ENC[AES256_GCM,data:kaFY8O8xJtGuecOpS6z+PPZk3fzHWD/wd4+gKwlCkH6LzUiU9IvJi61W0nJEAvZFT+d53SR0IaCFU901u2mfZM0vbo9lytVKxie/HWEBNOqkA7xN6iX3TwMoSRyMViStogBXUeQF9n5HzzIQdCmNjJBCLd1jpbMaYRxC8qC2U1A=,iv:DS0ZyEAyQhuGET1hW//wNK2Br/TXI4j2qaDJUccTbBo=,tag:bdGvp34qjY15oABR44bcHQ==,type:str]
  pgp:
    - created_at: "2026-05-14T22:51:17Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA4KMO5ZgOOZwAQwAth4+UpgRxi3h0ePQRKruo6pZYwu2UWcNFSokG1SPGwUs
        ydJQ4WB4TGxRnEjksvzgEtVgwp8mtu1ZrokDlNCzWchO+yiw8xuv/BkT2oFTcDVP
        1QF6ytnSXt9ZC/0sIKnHJgElzqMzMnms4aBOznqijOTmM2robA1W9u/79aCoT+IE
        NVSuJy7TZ/47qggAQLJOyfbBZMxlrHCGAp0P7EW9o7G3dflLHmEUdT6Q/84pOKr7
        5ISEYstRXqkTIC3FyjXQiF29XkIHzVhPDyk/AcVVfdn+Iwy+xcmfnEjHs7D+/1ym
        uBL7On2n2ZnCP9ZQ5zExmshY/5N2GjJbIKTJC4psQi3CU/IWHAhCDUwI7W4ohoDg
        gbFvLudJyZvQli87WscPslEVIfg/WwjPFvPKhyot1808pi1HUcsfPQLejEDhiXQZ
        scgF72cQuRPLD2qZrfWceEoG4avSi9iQLbmtoVHGMcnFtIbxkSl/fXW9Q//UUSwb
        IQob1Ps7TALb7hs+8Ddj0lwBrX4PL+bazS4LRRObB+HaxHVPNSTAcaeKjaYjcRYR
        x5KcjfyTUvZ6Okx/o2+CM/5RB1mVBLWwCb/MIGHPi6bKuC2fYQaPuDmksw9RlAEy
        QYgvxBZBsGd8ELNKRA==
        =D1mg
        -----END PGP MESSAGE-----
      fp: E751B57856FF4B3B7B4C7F5F3E041E30885ADDC3
  encrypted_regex: ^.+$
  version: 3.12.1
