# Terraform will be unable to decode this file if it does not contain valid YAML
# You can retain `---` (start of the document) to indicate an empty document.
inbound_rules:
    rdp_admins_inbound_allow:
        disabled: ENC[AES256_GCM,data:X4rL0qM=,iv:XNDenHyMq/GvNtf3ocwG/BwuZN4Dwkp08Eh8cIvXdws=,tag:jVrAMl/UP12w/L/SVNz9WA==,type:bool]
        deny: ENC[AES256_GCM,data:nlH00Gs=,iv:vVxBN1iUWILcG88dvLnPQJcdfK/irtf1CSK68loaxQw=,tag:m+Aw+LfYRafGdCdARqur7g==,type:bool]
        description: ENC[AES256_GCM,data:6u1mQrujJLXHFlNgFpmrth8bljIgRZrxIQ==,iv:gAuoN4U0Ec37eKrRIFP03AtGb+uuaGgNx4zmCh0cJ/8=,tag:3IJ5TujhRUuIMNb2TBFkQQ==,type:str]
        priority: ENC[AES256_GCM,data:5n9N,iv:56HR5gslSC/FOkjS2dDJ+R5ZPmPwkPRdic5pY2R2pOI=,tag:nzmJV6y2VsdxGcoo3LZmxQ==,type:int]
        protocol: ENC[AES256_GCM,data:wSfH,iv:pqGdhzq1BfEOJ9+sBJyD+fip87IDTCZqtochZEBdscc=,tag:tOHSciY/Zfe+FSOTlq5PLg==,type:str]
        source_port_range: ENC[AES256_GCM,data:cQ==,iv:QeY4SMHE8UMYXF0wgXh8N0sx2nmZ53KtmzBvsWyglY4=,tag:6AgBzrZHHZC3LYkuRUcpsg==,type:str]
        destination_port_range: ENC[AES256_GCM,data:dm+mUw==,iv:O4oROtmEng1t0ck2lAduzcv7NL76s+NnC9iRUG22nZ0=,tag:K/EE2Jy8O0M6Ah+oLe3dVg==,type:str]
        source_address_prefixes:
            - ENC[AES256_GCM,data:YynkQ3F054La,iv:51mgZZN8D3JVsphl/YG7rn0CLPyqQIwcutVbMQKMM4Y=,tag:WByj/2UzUHsGf36yEyd6zw==,type:str]
        destination_address_prefix: ENC[AES256_GCM,data:WA==,iv:Vp6OjbKYImzvJ5LbqPojoE9jD7FmxCm4+8yCSSMrgAE=,tag:k3Ugc5KRI0ZBJr/mJeeHcA==,type:str]
        associations:
            subnets:
                - ENC[AES256_GCM,data:4IB9,iv:wjsUV895FlbvUlco+0xGm5wfcYjVqVYhtClbcLXtd7E=,tag:IxllSlS3IdvaqP7tcn0fnQ==,type:str]
    winrm_admins_inbound_allow:
        disabled: ENC[AES256_GCM,data:KJ/eVw==,iv:u5cYMvB7S7XUQsIfEjLUg0so5Bkp9ILkkuMPQ8RsNfs=,tag:hh+oZDdAFTLiK8onJvAlPA==,type:bool]
        deny: ENC[AES256_GCM,data:D/Q3XXc=,iv:0DwYAcV/CNghdbKHTBEKwiIc1YfeA8FzB3fL/qmOWrE=,tag:q41GLor2W+3wVZJpW4rwCQ==,type:bool]
        description: ENC[AES256_GCM,data:g6xyyka/bR79gTQ0N+kLRKcRNm8VbduKoVpbpuY=,iv:5b8nNVLjhw2QlKkBCz0fTUU1noptuCmISXucyqtLigY=,tag:qmpfzG2KjI6PJdadbN5E0g==,type:str]
        priority: ENC[AES256_GCM,data:av6n,iv:0ngmlftDOL1HB8WMLflddAQ9f89jLBG96iHGtbHOgvI=,tag:7kTjHF5o4KcQwCI81/lz7w==,type:int]
        protocol: ENC[AES256_GCM,data:qy6X,iv:lG27cZlVpV605oqwh5H0xa0Wg2E6NlyBD5dVj5JwcHI=,tag:uzpSvrQQuw6UKvOXTnF3MA==,type:str]
        source_port_range: ENC[AES256_GCM,data:Mg==,iv:5p53fPx6FyB6oWTRnI2Xp7QLVo1GXFPEeTN5yai2QuA=,tag:bhFvA7GgI4Ac5wOZ+nNCfw==,type:str]
        destination_port_range: ENC[AES256_GCM,data:FffQag==,iv:VO5HwBpzeHX47uJIraalBhPb34Q91a6uePLTj2Dbwlg=,tag:Kj5jOwR8CThmEsv4eVeYTQ==,type:str]
        source_address_prefixes:
            - ENC[AES256_GCM,data:JFkHX67Et/9w,iv:ficWrBEMvKvv38OOM/HaInBWkPxoVB3S0+DdlA2b73U=,tag:RlRALWrYaA9tnoZg49r6Qw==,type:str]
        destination_address_prefix: ENC[AES256_GCM,data:Cw==,iv:IFKxaKsdFfpTq5CHDqkX0KBVIPjLvlzWFXtO22E+DuQ=,tag:gLbheOx1rB+mD1wCC1QQ2A==,type:str]
        associations:
            subnets:
                - ENC[AES256_GCM,data:Sh1C,iv:90TpJNtxiHG69/5Ux6CtGp/aB5NIyU+7qTHxR96MtWM=,tag:3jkqO1k73gcmbFLR0G6/KQ==,type:str]
outbound_rules:
    all_outbound_allow:
        disabled: ENC[AES256_GCM,data:9YKTIg==,iv:aD1EFnSgy65kAq6yG+7Qi26evkkrc4H/deSOQvUs6T0=,tag:dnY1BCYsQacO7ubD+rBuLQ==,type:bool]
        description: ENC[AES256_GCM,data:ym8g66R6EqcSCk08GGU99Zw7Cax/BgLrnA==,iv:zJP9lHy9pdux4RtEcBs9dCNNtuQEbC+TiDfhEYdAeQA=,tag:dODNI7JfxNZqmfzcpuNaNw==,type:str]
        priority: ENC[AES256_GCM,data:4+qe,iv:16GxOV14lJf6SeUsSxTloWFlQQYrCiMconqHxEdUYUQ=,tag:8wHJHPhE7ce9D4cePEK7Gw==,type:int]
        protocol: ENC[AES256_GCM,data:tg==,iv:M+qITooEpQEVjj1qwKG9ugRWLVlDQD/ehRdwwow7o94=,tag:iw5HW5JFXduCP8wV3vxRcA==,type:str]
        source_port_range: ENC[AES256_GCM,data:YA==,iv:NrDM1CQQQKfc3yaDxq5iQQ4tHZ0DTXuE4XailUKmxuE=,tag:EjiE5N2gyYh7ircA8vHaSg==,type:str]
        destination_port_range: ENC[AES256_GCM,data:/w==,iv:PRELVd3HEFEydVS/tpXEPykHbKqO8ascO90EuyxNdu0=,tag:JJFbanZV+N6RJGFPKyHezg==,type:str]
        source_address_prefix: ENC[AES256_GCM,data:4A==,iv:dbVgR9XjfqZVDPUqKiZjz44Y6GnU3TeiSrAEksO1Qko=,tag:gUEMAw416NX5P9Aw7Gt2qw==,type:str]
        destination_address_prefix: ENC[AES256_GCM,data:Pg==,iv:EThhYjeAbUJSZ/kdQ6USVMk78z3Ygl/nhMXl+1YGBoM=,tag:ooi3Bb4XEJ4PuIMBi90W2w==,type:str]
        associations:
            subnets:
                - ENC[AES256_GCM,data:vzPM,iv:LO1G3khVUPwt+41TTWPJzZivbCDGA4lw0euVpiC8Lt8=,tag:kvYsuTVWZjwJ1Okg5M10tA==,type:str]
    rfc1918_outbound_allow:
        disabled: ENC[AES256_GCM,data:t+VChg==,iv:LewYXRjq4+ca0U0G+Yp1K0dF+ZQwNGgr7jBA10S0CWA=,tag:1GC3x3iuq15i0DYrMH8qhQ==,type:bool]
        description: ENC[AES256_GCM,data:CiUAvWSo1Uags8UU1xJTF2A/vO45x70zxND8woVdh3g=,iv:lx3dNEsS4/AJCzY7LcdSY0+chphnSpD/g4+lMq189m0=,tag:f+ZAeF5Zndv3sYMm0zS6AA==,type:str]
        priority: ENC[AES256_GCM,data:VMt7,iv:JM1HRqj4CiuqnF4N/SwTYx93xXOWiigTi1aea7iRv/o=,tag:6BqKPQEMHJF3rmVz2wP+4A==,type:int]
        protocol: ENC[AES256_GCM,data:+A==,iv:qWLiyM72DeUV87FvNOD+IRxxSAVRHUu3+eNIhA17kls=,tag:eVK0VDKcCnoEe6pnHFU0FA==,type:str]
        source_port_range: ENC[AES256_GCM,data:ig==,iv:IDAsdzau0KBEzBQDobCDo5nxi2k5EmDb2v2zEXn+o7g=,tag:344LhLwhQwoBw6fQ5az+9g==,type:str]
        destination_port_range: ENC[AES256_GCM,data:Qw==,iv:Yus9v9VZAfvohHZmitPMmgY5xoV1GTg62q0qO/2r61g=,tag:CQMk8TN9RR25R2zZVF6kAA==,type:str]
        source_address_prefix: ENC[AES256_GCM,data:nA==,iv:qy+ppp4zJZ/M4+XlL4u1zHVlhQr+FmefEoEjlA56TgQ=,tag:gZaN1/6QYJF5kwPJMHiarQ==,type:str]
        destination_address_prefixes:
            - ENC[AES256_GCM,data:3L8U+nncbrhhCg==,iv:C33+l3Od6/mfow90pfWu9ssWBq1rtRH/Vbgq6GpzqMo=,tag:vmApMfGat4bAVpluonUeRA==,type:str]
        associations:
            subnets:
                - ENC[AES256_GCM,data:8FgV,iv:Up84xmXE9cltjs5Wc6NoI+U2RX4ElCvbHtSNInO0Dho=,tag:SA6HYgCDF7JDH9M6MnjRoA==,type:str]
sops:
    lastmodified: "2026-05-14T22:50:10Z"
    mac: ENC[AES256_GCM,data:4d6saETSH/sgXQ0fp6d/L45iotJL3mRI+tgVsJTLz6ABpM2JYBtAvbhPGUQUv6etgpC68VOC5jJPs7V5k1wiVm7RdnAplZQGpth7ZkT4QH4h/oEjTnx/ehuTJzZ9H0YxO4rm9KJJYViUd2iRKZH06dLqsYQ+XP2Hk8RuesvbEcI=,iv:bnPYVgPs0YgPtxAS8uT9GcEGL2irQ+EZLye35xLLW+Y=,tag:7Zt32tDbQdKYFTf33nzpvg==,type:str]
    pgp:
        - created_at: "2026-05-14T21:59:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA4KMO5ZgOOZwAQwApLMf5BZexjuYdlGcXAAdYmn7qh+G3nwziejVCj3RqLBh
            fN6RSH/MFiqhoQAHrLrPabxSR7oqv5DeqAZNx6qBXib2FoOb+xbp4GmCMD7baBfG
            v6wQQDOEcqdG8mL4bPQD4rBsAhgfWTyvt8zOo+XZuj3klDEAIvtm75l3KUX38ykY
            vhchCvC+aq4uxrZdbUPaRWoE0922WUxepFt5NgCU5HvUviKO4PkgE7pYE9kLHq9A
            Ep+dA8xCM3qmR/WnbAdXvrwXhFs73gCcO7Hpxms22+Ydw1RkCqBu6L7SUbo3X0WF
            htY2IOKzT+zECobqn+3sShLR+63QiCUmcnGqMIeONV9iUuQvW9eDDBiHKn91spFZ
            rf8vga9sUfk8bTWyyqWERvUvEuFlUELsmf+neCu17WvdsdmBWzijQdp4c5C9i6jX
            DuzXejAwBoBjGCAS4K+YeE1R+VywEoMMLwZN2bBmYg4IeCot9GCp5jYrplAF7DYa
            PjLQ0QVOwXOVsMkuiE9L0lwBxixBT9B0Cyf4GSB4vyWM3z0G/Bd3cnMlbv61ZWvE
            zt6s3/0UMhBVlnj81FlBBifmZP9sDxZ1QFLt/hZupqQAJDUaFM1qIwyNDxYd7i8T
            Sl8P00DuG4TlDfXxFQ==
            =IJUo
            -----END PGP MESSAGE-----
          fp: E751B57856FF4B3B7B4C7F5F3E041E30885ADDC3
    encrypted_regex: ^.+$
    version: 3.12.1
