# Terraform will be unable to decode this file if it does not contain valid YAML
# You can retain `---` (start of the document) to indicate an empty document.
inbound_rules:
    all_inbound_allow:
        disabled: ENC[AES256_GCM,data:Wt8GQQ==,iv:fl4DDnDupbQX5QIqgqpA7yucItWnVOJqDJDfh3iYtyY=,tag:s3GM1huyHiUaSf3rYTvahA==,type:bool]
        deny: ENC[AES256_GCM,data:bwM8ROc=,iv:0cdam5XEcWdtEOUHVkdZg4p+GNvPH9CJifV3V6slVx0=,tag:JpocjAhcEP+5+bJ+W25CYw==,type:bool]
        description: ENC[AES256_GCM,data:wftRbm38iBz4RO0L,iv:YxznFyTJ8GkKnw05StNjjrJ369db6+ydIVz/0zb+cCY=,tag:BXdL89LDU4vni76os8xMGw==,type:str]
        priority: ENC[AES256_GCM,data:UC0O,iv:7oFOA0VlILrszz6qRRRtxvrXcZgg3d5QIWzXumBcVBc=,tag:BrDWMOTkdi9Xp7cLxYWwKA==,type:int]
        protocol: ENC[AES256_GCM,data:HA+Q,iv:OEpBhbEriXEKqFbRF7DrPp82nV/Zu6yeeVy/Bl4SfHE=,tag:9Wdm9BDzgylllFqYhzOyHw==,type:str]
        source_port_range: ENC[AES256_GCM,data:5w==,iv:+XdpsAc6gA4RAORy3WEr0zbp3oHRPOxyHGEjanOx78w=,tag:2cLAVuSBA2aq+oWx8b3cMA==,type:str]
        destination_port_range: ENC[AES256_GCM,data:Hkg=,iv:QMhBXHBjvZQqtKUnudcKHZ2rfPQ0Lxn/LgBNMdBGIkw=,tag:0qQtgopNPM35rOMmhEX/+Q==,type:int]
        source_address_prefix: ENC[AES256_GCM,data:ew==,iv:mAhhqhgY4xM8eEl8naD9SPQALiiFLoxDjP3h532rUUI=,tag:hwkbJaqlVlIvZArjc/B9qA==,type:str]
        associations:
            subnets:
                - ENC[AES256_GCM,data:zQ==,iv:e3MPzQVBsGNclhl2w3aedgJDgvKFUr13i5Xw2915Jmw=,tag:XmuZHs+CcDu3V5wByDz/9g==,type:str]
    rfc1918_10_inbound_allow:
        disabled: ENC[AES256_GCM,data:/ff7Ng==,iv:D0nb+eiI0Ik+u2GVgCkWjYGcBGXc4XdncIQ74cc+7Gs=,tag:OkzCbAMNHI4juM8bf2gfBw==,type:bool]
        deny: ENC[AES256_GCM,data:BrjtkGs=,iv:Jl9jtK+Skj4y4k7ML3K3LOFjVpLd5q0r5VeoqE9EE0E=,tag:HdlEqwkmM7RmYkIJ35Y/OQ==,type:bool]
        description: ENC[AES256_GCM,data:OitvGiV81EPpQjL3,iv:QbRngqd5JZbACCu/fPiYULEKVn/h7N7uS65cFs6WIOc=,tag:Qbmaq/jJ4+NphawFzhLomA==,type:str]
        priority: ENC[AES256_GCM,data:QYHK,iv:kJQh/Nv7cdVu+ztqa8/JwWHtEkJUPMgNPGVOqek6VAc=,tag:u8blq/C0PtYQPL8MzjGeOg==,type:int]
        protocol: ENC[AES256_GCM,data:2g==,iv:AtA6cW39OfZvXfoX3u1TsfgsmDrROjB4/6W8xnHhtZ0=,tag:PrxT+IhM0JpScSFi6pJyjw==,type:str]
        source_port_range: ENC[AES256_GCM,data:dQ==,iv:3vu+LHo2QXkyAK494W/lDuCYLnTJs3KJxqZuXAs2IxQ=,tag:/JKfoWT7gl1f09nhQgpvIQ==,type:str]
        destination_port_range: ENC[AES256_GCM,data:LQ==,iv:M+srfr6JJUFeZWotdLq0RzT+qt5o5xSlmErc8DhMspw=,tag:OAay/h8RZtnB3LjWdLl/iA==,type:str]
        source_address_prefixes:
            - ENC[AES256_GCM,data:yWduqTgXo6tU5Q==,iv:dpqFjVy9l8v1NE1aenxhACetdLSiZR9vVhugn0Ny22I=,tag:J+6qBYqNiSsfXZ5ZBc0A7w==,type:str]
        destination_address_prefix: ENC[AES256_GCM,data:ig==,iv:VFAWP4WdrSEZhVnaPLcR/sPNZV4+vgFVMEwi0ZXMiPU=,tag:ndIO5s5h2rylCCshowIfoA==,type:str]
        associations:
            subnets:
                - ENC[AES256_GCM,data:ufpB,iv:XXE5Hs48qiz6ADJYPxD5Ocxir7Ey6Mc/fDdtFtk3vBI=,tag:P3B3xs8boJD1SKZXiJG/xA==,type:str]
outbound_rules:
    rfc1918_outbound_allow:
        disabled: ENC[AES256_GCM,data:UG4e+0c=,iv:jsaD0LM1IZaU3LPC6bgvlJwRCm2XoIthBYoKjBrXrQg=,tag:lNBjtOXY9sjXhoZXIIIHcg==,type:bool]
        description: ENC[AES256_GCM,data:/sMrUgyyZpetOPXApLHbu/jyrqPIP1WWsZzKzBY=,iv:l/wi6dpgbxI/T7KTfFcN8Muv/MFfxyg4DO+v+3sCikw=,tag:cm2Xspyux9llDzMy8Nj6Iw==,type:str]
        priority: ENC[AES256_GCM,data:tTxB,iv:rD5BLhtFBJLAsRPx82ZM+i8u2tD74sI61Vhph/HeUzI=,tag:vZ5GuoNi5Ybq8ywOCUGKxg==,type:int]
        protocol: ENC[AES256_GCM,data:XQ==,iv:wZlurJ+RO2gJPU9UzOF/J2+JfPk1Awf/8rbd1Vg+atI=,tag:cbwMqjRIW09Md2XHVxUg2A==,type:str]
        source_port_range: ENC[AES256_GCM,data:RQ==,iv:KwzUQUKgyvjsIofU2vYX8pMycY+J1yrpF36mgQN7zKQ=,tag:TH1PBxoUbUzAuJLN53YexQ==,type:str]
        destination_port_range: ENC[AES256_GCM,data:gA==,iv:93W6K/QzycKFQgR6JnPicxMTXpTcQ3xrRyi+9GVTs4k=,tag:zcUQ1rMr8iVJWavpUafWww==,type:str]
        source_address_prefix: ENC[AES256_GCM,data:4Q==,iv:J+EYZZuoaUBzGLw6ML0Np2jpb8i8bgLqlTeEozM35Z0=,tag:8u85OWbCAwoTzLOXrTcgOw==,type:str]
        destination_address_prefixes:
            - ENC[AES256_GCM,data:Irhk3QVJrA==,iv:aIqMua6HqrRD9xMfd8XKrJD2bG/BI/fliCSXsGVIu2w=,tag:SH8BvL2+qAof9b9aEBDlIw==,type:str]
        associations:
            subnets:
                - ENC[AES256_GCM,data:dGiS,iv:BAHAE04QUJCDXBbVZ10eu4VV8XtiP6uCtGSwdC6cxQM=,tag:b8BACMu1cedGJuMU1aMR6w==,type:str]
sops:
    lastmodified: "2026-08-06T07:58:29Z"
    mac: ENC[AES256_GCM,data:B2hmFnoDqsOl6RvHSoKKqrg4QnEUfUbY5dKmBO2+V90AwoL2P1KcLiI/4cKA/0ySTtS8zsbxx09260W8kG9STpx9ZngH00y/C8OitRklY3j0frlVFyDBn70hYQrpG3/rxxqMmoyNLTcWf6SVfWI5EQpY8Y52JM6I5PJFMzZIBC4=,iv:Nm3scXnpiunQJsAOg6PgRGjgkUIRr1mliF6dtpk3hZM=,tag:MZXIfAwnTcO4py2SFmBLXQ==,type:str]
    pgp:
        - created_at: "2026-05-14T21:51:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA4KMO5ZgOOZwAQv/eFa2CHD//67SkKj1GWRaJ8V31xc/CfFEqf4hP9Q09NGg
            KIG3iAF1HefY3iipskB+UlGzBVzsa6djXr4M/mPvcHWMAZupdIkVFPsbHvIhvYM6
            PtRTZlq299wzpnZTGRJUsqPqn5t86rfyJCZcPKuFLj0ZVmBcAZCoybAECqLhgFGG
            0gVwNi2g7UI1iB+M2Fae3Gx2gE6TLWW+F4XxirDvJ5JN+v5PZjU4YBXCs7zeqPhd
            HQY7E0ss7siHMB3KmKpHe/RzxFA2OEl5grgQpkPdIutvWHfh+920pUXnfMyiAUk1
            I9zr4l+RZX8iww0VKwgeWAXnLH/XBj8tob+oJnCqwuUqFVbIn1e8TCbZZhYXcX9A
            VqPh+8Y3ZMkY0bGUri2enrnHEjKEtfxlLl2zYhJ+j5t/liZmU2pYzY191DsYSYCW
            TmwvwncvgJRdgxSaCT4C/+Jm7dbBRx/AXlS1cuR/j1vEFtPUlkpm9alEEY+rsSrM
            jY06ap7Sk069hHNAqm6S0l4BCG/WMX1/rFQkue+I9s/KTaeDr7eOBKCUS0r5AgRd
            KXfMvt6Hx3rZsPR7jX9aUl5jeVkU3tMUVakds57PeZ5nd6TPUygX6lVtACY/zZe9
            2wn8fTZKKMNTahby3YiI
            =2UkA
            -----END PGP MESSAGE-----
          fp: E751B57856FF4B3B7B4C7F5F3E041E30885ADDC3
    encrypted_regex: ^.+$
    version: 3.12.1
